## Cheat sheet for `Numpy`

In [3]:
import numpy as np
# check for version
np.__version__

'1.26.4'

### `Ndarray` class
`Numpy` array class is called `ndarray`. Function to create - `array`
`ndarray` has the following attributes:
1) `ndim`  - number of dimensions or axes of the array (scalar - 0)
2) `shape` - tuple of non-negative integers that specify the number of elements in each dimension
3) `size`  - total number of elements in the array
4) `dtype` - data type (list of data types??)
5) `itemsize` - length of one array element in `bytes`.
#### Notes:
* Indexing starts normal, from 0 (unlike `R`)
* Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 

In [4]:
arr = np.array([[[1, 3, 5, 7], [9, 11, 13, 15]], [[2, 4, 6, 8], [10, 12, 14, 16]]])
print(f"ndim  =  {arr.ndim}")
print(f"shape =  {arr.shape}")
print(f"size  =  {arr.size}")
print(f"dtype =  {arr.dtype}")

ndim  =  3
shape =  (2, 2, 4)
size  =  16
dtype =  int64


### Create array
1) `zeros(shape)`              - filled with 0
2) `ones(shape)`               - filled with 1
3) `empty(shape)`              - filled with random values (faster than `ones` and `zeros`) 
4) `arange(start, stop, step)` - same as range
5) `linspace(start, stop, num, endpoint, retstep)` - array with values that are spaced linearly in a specified interval:


#### Notes:
* Default data type is `float64`
* `num` is defaulted to 50
* `endpoint` indiactes whether the end should be included (default `True`)

In [13]:
print(f"{np.zeros((1, 2))=}")
print(f"{np.ones((2, 3))=}")
print(f"{np.empty((2, 3, 1))=}")
print(f"{np.arange(5)}")

print(f"{np.linspace(1, 5, 1)=}")

print(f"Without endpoint: \n {np.linspace(1, 5, 5, endpoint=False)}")
print(f"With retstep returns both array and step: \n {np.linspace(7, 8, 5, retstep=True)}")



np.zeros((1, 2))=array([[0., 0.]])
np.ones((2, 3))=array([[1., 1., 1.],
       [1., 1., 1.]])
np.empty((2, 3, 1))=array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])
[0 1 2 3 4]
np.linspace(1, 5, 1)=array([1.])
Without endpoint: 
 [1.  1.8 2.6 3.4 4.2]
With retstep returns both array and step: 
 (array([7.  , 7.25, 7.5 , 7.75, 8.  ]), 0.25)


### Adding, removing, and sorting elements
1) `np.sort()` - sort along axis
2) `np.concatenate()` - concat along axis
3) `np.reshape()`


In [17]:
arr = np.array([1, -5, -7, 8, 10, -3, 4])
print(f"Initial array: {arr} \n sort: {np.sort(arr)}")

print(f"concat initial and sorted: {np.concatenate((arr, np.sort(arr)))}")

arr = np.empty((2, 3))
print(f"Before sorting: {arr}  Sort along 0 axis: {np.sort(arr, axis=0)}")

print(f"reshape: {np.reshape(arr, (arr.size))}")



sort: [-7 -5 -3  1  4  8 10]
concat: [ 1 -5 -7  8 10 -3  4 -7 -5 -3  1  4  8 10]
Before sorting: [[1. 1. 1.]
 [1. 1. 1.]]  Sort along 0 axis: [[1. 1. 1.]
 [1. 1. 1.]]
reshape: [1. 1. 1. 1. 1. 1.]


ndmin - ?