## Cheat sheet for `Numpy` with examples

In [1]:
import numpy as np
# check for version
np.__version__

'1.26.4'

## `Ndarray` class
`Numpy` array class is called `ndarray`. Function to create - `array`
`ndarray` has the following attributes:
1) `ndim`  - number of dimensions or axes of the array (scalar - 0)
2) `shape` - tuple of non-negative integers that specify the number of elements in each dimension
3) `size`  - total number of elements in the array
4) `dtype` - data type (list of data types??)
5) `flat` - returns 1-D flatten iterator over the array
6) `itemsize` - length of one array element in `bytes`.
#### Notes:
* Indexing starts normal, from 0 (unlike `R`)
* Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 

In [9]:
arr = np.array([[[1, 3, 5, 7], [9, 11, 13, 15]], [[2, 4, 6, 8], [10, 12, 14, 16]]])
print(f"ndim  =  {arr.ndim}")
print(f"shape =  {arr.shape}")
print(f"size  =  {arr.size}")
print(f"dtype =  {arr.dtype}")
print(f"flat =  {arr.flat}")
print(f"flat (converted to array) =  {np.asarray(arr.flat)}")
print(f"itemsize =  {arr.itemsize}")


ndim  =  3
shape =  (2, 2, 4)
size  =  16
dtype =  int64
flat =  <numpy.flatiter object at 0x5cbc9f0212e0>
flat (converted to array) =  [ 1  3  5  7  9 11 13 15  2  4  6  8 10 12 14 16]
itemsize =  8


## Creation of  `ndarray`

* #### Intrinsic:
1) `zeros(shape)`              - filled with 0
2) `ones(shape)`               - filled with 1
3) `empty(shape)`              - filled with random values (faster than `ones` and `zeros`) 
4) `arange(start, stop, step)` - same as range
5) `linspace(start, stop, num, endpoint, retstep)` - array with values that are spaced linearly in a specified interval
6) `random.random(shape)` - returns array of shape of random values in half-open interval [0, 1)
7) `random.randint(min, max_exc, shape)` - returns array of ints, of shape shape starting from min, excluding max_exc

* #### From existing data:  
1) `ones_like(ndarray)`
2) `zeros_like(ndarray)`

* #### Notes:
* Default data type is `float64`
* `num` is defaulted to 50
* `endpoint` indiactes whether the end should be included (default `True`)

In [6]:
print("Intrinsic: ")
print(f"np.zeros(2,3) = \n {np.zeros((2, 3))}")
print(f"np.ones(2,3) = \n {np.ones((2, 3))}")
print(f"np.empty(3, 4) = \n {np.empty((3, 4))}")
print(f"np.arange(5) = \n {np.arange(5)}")

print(f"np.linspace(1,5,1) = \n {np.linspace(1, 5, 5)}")

print(f"Same Linspace Without endpoint: \n {np.linspace(1, 5, 5, endpoint=False)}")
print(f"With retstep returns both array and step: \n {np.linspace(7, 8, 5, retstep=True)}")

print(f"np.random.random(3, 3) = \n {np.random.random((3, 3))}")
print(f"np.random.randint(0,10,(3,3)) = \n {np.random.randint(0, 10, (3,3))}")

print("\n From existing data: ")
X = np.array([[0, -1, 2], [10, 14, 12]], dtype=np.int64)
print(f"Original array X = \n {X}")
print(f"ones_like(X) = \n {np.ones_like(X)}")



Intrinsic: 
np.zeros(2,3) = 
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones(2,3) = 
 [[1. 1. 1.]
 [1. 1. 1.]]
np.empty(3, 4) = 
 [[5.03705198e-310 0.00000000e+000 1.01855798e-312 9.54898106e-313]
 [1.08221785e-312 1.01855798e-312 1.23075756e-312 1.10343781e-312]
 [1.03977794e-312 9.76118064e-313 1.01855798e-312 1.90979621e-312]]
np.arange(5) = 
 [0 1 2 3 4]
np.linspace(1,5,1) = 
 [1. 2. 3. 4. 5.]
Same Linspace Without endpoint: 
 [1.  1.8 2.6 3.4 4.2]
With retstep returns both array and step: 
 (array([7.  , 7.25, 7.5 , 7.75, 8.  ]), 0.25)
np.random.random(3, 3) = 
 [[0.38779146 0.30322875 0.11940438]
 [0.8378572  0.3396763  0.14646799]
 [0.02900885 0.9350037  0.90565372]]
np.random.randint(0,10,(3,3)) = 
 [[8 7 4]
 [7 8 0]
 [1 9 8]]

 From existing data: 
Original array X = 
 [[ 0 -1  2]
 [10 14 12]]
ones_like(X) = 
 [[1 1 1]
 [1 1 1]]


### Adding, removing, and sorting elements
1) `np.sort()` - sort along axis
2) `np.concatenate()` - concat along axis
3) `np.reshape()`


In [ ]:
arr = np.array([1, -5, -7, 8, 10, -3, 4])
print(f"Initial array: {arr} \n sort: {np.sort(arr)}")

print(f"concat initial and sorted: {np.concatenate((arr, np.sort(arr)))}")

arr = np.empty((2, 3))
print(f"Before sorting: {arr}  Sort along 0 axis: {np.sort(arr, axis=0)}")

print(f"reshape: {np.reshape(arr, (arr.size))}")



sort: [-7 -5 -3  1  4  8 10]
concat: [ 1 -5 -7  8 10 -3  4 -7 -5 -3  1  4  8 10]
Before sorting: [[1. 1. 1.]
 [1. 1. 1.]]  Sort along 0 axis: [[1. 1. 1.]
 [1. 1. 1.]]
reshape: [1. 1. 1. 1. 1. 1.]


ndmin - ?